name: customized_html_editor
description: "html_editor"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # webview plugin
  flutter_inappwebview: ^6.1.5
  # plugin to get webview's visible fraction for keyboard height adjustment
  visibility_detector: ^0.4.0+2
  # plugin to get when the keyboard is hidden via back (Android)
  # or "done" (iOS) to reset the editor's height
  flutter_keyboard_visibility: ^6.0.0
  # plugin to show a color picker for foreground/highlight color
  flex_color_picker: ^3.6.0
  # plugin to get files from filesystem
  file_picker: ^8.1.4
  # plugin to show a scrollable number picker for inserting tables
  numberpicker: ^2.1.2
  # plugin to allow dropdowns and dialogs to be interactable when displaying over the editor
  # related to https://github.com/flutter/flutter/issues/54027
  # pinned to 0.9.1 because of issues with CanvasKit in the latest versions
  pointer_interceptor: ^0.10.1+2
  # plugin to help maintain effective Dart standards
#  lints: ^5.0.0
  # plugin for @internal annotation
  meta: '>=1.0.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/customized_html_editor/assets/summernote.html
    - packages/customized_html_editor/assets/summernote-no-plugins.html
    - packages/customized_html_editor/assets/summernote-lite.min.css
    - packages/customized_html_editor/assets/summernote-lite-dark.css
    - packages/customized_html_editor/assets/summernote-lite.min.js
    - packages/customized_html_editor/assets/jquery.min.js
    - packages/customized_html_editor/assets/font/summernote.eot
    - packages/customized_html_editor/assets/font/summernote.ttf
    - packages/customized_html_editor/assets/plugins/summernote-at-mention/summernote-at-mention.js
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
